PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail # Treat all warnings as failures

  TrailingWhitespace:
    enabled: true

CommitMsg:
  CapitalizedSubject:
    enabled: false

  MessageFormat:
    enabled: true
    pattern: ^(\((doc|bug|feat|security|dev|i18n|api|test|quality|ui|merge|wip)\) [\w ]++(\n\n.+)?)|(Version (\d+\.?)+)|(Merge branch .*)
    expected_pattern_message: (doc|bug|feat|security|dev|i18n|api|test|quality|ui|merge|wip) title\n\ndescription
    sample_message: (bug) no validation on date\n\nThe birthdate was not validated...

