require: rubocop-rails

AllCops:
  NewCops: enable
Layout/LineLength:
  Max: 140
Metrics/MethodLength:
  Max: 35
Metrics/CyclomaticComplexity:
  Max: 14
Metrics/PerceivedComplexity:
  Max: 14
Metrics/AbcSize:
  Max: 45
Metrics/ClassLength:
  Max: 210
Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'lib/tasks/**/*.rake'
    - 'config/routes.rb'
    - 'app/pdfs/pdf/*.rb'
    - 'test/**/*.rb'
    - '**/*_concern.rb'
Metrics/ParameterLists:
  CountKeywordArgs: false
Style/RegexpLiteral:
  EnforcedStyle: slashes
Style/EmptyElse:
  EnforcedStyle: empty
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/AndOr:
  EnforcedStyle: conditionals
Style/FormatString:
  EnforcedStyle: sprintf
Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false
Rails/UnknownEnv:
 Environments: development, test, staging, production
