# configuration file for Sidekiq
:verbose: true
:logfile: ./log/sidekiq.log
:concurrency: 5
:queues:
  - [stripe, 7]
  - [default, 5]
  - [devise_mailer, 3]
  - [mailers, 3]
  - [elasticsearch, 2]
  - [system, 1]
